---
language: node_js
node_js:
  # Using the same minimum supported node version as Ember CLI & Lerna
  - '6'

sudo: true  

addons:
  chrome: stable  

cache:
  directories:
    - $HOME/.npm
    - $HOME/packages/*/.npm
    - $HOME/packages/*/.cache # includes bowers cache

env:
  matrix:
    - PACKAGE=navi-app
    - PACKAGE=navi-core
    - PACKAGE=navi-dashboards
    - PACKAGE=navi-data
    - PACKAGE=navi-reports
    - PACKAGE=navi-visualizations

matrix:
  fast_finish: true

before_install:
  - npm config set spin false
  - npm --version
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install

script:
  - lerna run test --scope $PACKAGE
