elide:
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
  async:
    enabled: true
    threadPoolSize: 7
    maxRunTime: 65
    cleanupEnabled: true
    queryCleanupDays: 7
    defaultAsyncQueryDAO: true
  aggregation-store:
    enabled: true
    default-dialect: H2
  dynamic-config:
    enabled: true
    path: demo-configs

spring:
  application:
    name: NaviWS
  jpa:
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.H2Dialect'
      ddl-auto: 'none'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
    username: 'navidev'
    password: ''
    driver-class-name: 'org.h2.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
    enabled: true
    contexts: non-test
server:
  port: 8080

logging:
  path: /tmp

---

spring:
  profiles: test
  liquibase:
    contexts: test
